services:

  postgresdb:
    image: 'postgres:alpine'
    restart: always
    environment:
      - 'POSTGRES_DB=project_team_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'